'use strict';
var YASMIJ = require('./src/YASMIJ.base.js');
require('./src/YASMIJ.Expression.js');
require('./src/YASMIJ.Constraint.js');
require('./src/YASMIJ.Input.js');
require('./src/YASMIJ.Matrix.js');
require('./src/YASMIJ.Tableau.js');
require('./src/YASMIJ.Output.js');
require('./src/YASMIJ.Simplex.js');
module.exports = YASMIJ;
